name: avr-miner
version: '4.3'
summary: Duino-Coin Official AVR Miner
description: |
  Duino-Coin Official AVR Miner 4.3 © MIT licensed
  https://duinocoin.com
  https://github.com/revoxhere/duino-coin
  Duino-Coin Team & Community 2019-2024

grade: stable
confinement: strict

platform:
  - linux

architectures:
  - amd64

apps:
  avr-miner:
    command: bin/avr-miner
    plugs: [network, network-bind]
    damon: simple
    restart-condition: always

parts:
  avr-miner:
    plugin: python
    source: .
    source-subdir: src
    stage-packages:
      - python3
      - python3-pip
    requirements:
      - requirements.txt
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp $SNAPCRAFT_PART_SRC/AVR_Miner.py $SNAPCRAFT_PART_INSTALL/bin/avr-miner
      chmod +x $SNAPCRAFT_PART_INSTALL/bin/avr-miner